`MACHINE LEARNING | ANALÍA ELIZABETH GOMORY | ARGENTINA – SALTA 4400 | 2024`

**by Analía Elizabeth Gomory**

* ae.gomory@gmail.com

* http://www.linkedin.com/in/elizabeth-gomory-9240b1217

* https://ae-gomory.itch.io

* https://github.com/ElizabethGomory

* https://www.credly.com/users/analia-gomory

* https://orcid.org/0009-0003-0498-7658

#### Importación de librerías y archivo ".xlsx"

In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df_titanic = pd.read_excel('/content/titanic_M1.xlsx')

### **1.** Descripción de valores faltantes en Base de Datos

In [16]:
df_titanic

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,2113375.0,B5,S,2,2.0,"St Louis, MO"
1,1.0,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,1515500.0,C22 C26,S,11,2.0,"Montreal, PQ / Chesterville, ON"
2,1.0,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,1515500.0,C22 C26,S,2,2.0,"Montreal, PQ / Chesterville, ON"
3,1.0,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,1515500.0,C22 C26,S,2,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,1515500.0,C22 C26,S,2,2.0,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1214,3.0,0,"Smiljanic, Mr. Mile",male,2.0000,0,0,315037,86625.0,2,S,2,2.0,2
1215,3.0,0,"Smith, Mr. Thomas",male,2.0000,0,0,384461,77500.0,2,Q,2,2.0,2
1216,3.0,1,"Smyth, Miss. Julia",Mujer,2.0000,0,0,335432,77333.0,2,Q,13,2.0,2
1217,3.0,0,"Soholt, Mr. Peter Andreas Lauritz Andersen",male,19.0000,0,0,348124,76500.0,F G73,S,2,2.0,2
1218,3.0,0,"Somerton, Mr. Francis William",male,30.0000,0,0,A.5. 18509,80500.0,2,S,2,2.0,2

In [10]:
df_titanic.dtypes

pclass       float64
survived       int64
name          object
sex           object
age          float64
sibsp          int64
parch          int64
ticket        object
fare         float64
cabin         object
embarked      object
boat          object
body         float64
home.dest     object
dtype: object

In [11]:
df_titanic.isna()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,False,False,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,False,True,True,False
3,False,False,False,False,False,False,False,False,False,False,False,True,False,False
4,False,False,False,False,False,False,False,False,False,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1214,False,False,False,False,True,False,False,False,False,True,False,True,True,True
1215,False,False,False,False,True,False,False,False,False,True,False,True,True,True
1216,False,False,False,False,True,False,False,False,False,True,False,False,True,True
1217,False,False,False,False,False,False,False,False,False,False,False,True,True,True
1218,False,False,False,False,False,False,False,False,False,True,False,True,True,True

In [12]:
df_titanic.isna().sum()

pclass         76
survived        0
name            0
sex             0
age           239
sibsp           0
parch           0
ticket          0
fare            0
cabin         927
embarked        2
boat          751
body         1110
home.dest     475
dtype: int64

### **2.** **Columna pclass:** completar valores NA = asignación de "clase 2"

In [23]:
titanic = df_titanic
titanic['pclass']=titanic['pclass'].fillna(2.0)
titanic

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,2113375.0,B5,S,2,2.0,"St Louis, MO"
1,1.0,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,1515500.0,C22 C26,S,11,2.0,"Montreal, PQ / Chesterville, ON"
2,1.0,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,1515500.0,C22 C26,S,2,2.0,"Montreal, PQ / Chesterville, ON"
3,1.0,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,1515500.0,C22 C26,S,2,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,1515500.0,C22 C26,S,2,2.0,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1214,3.0,0,"Smiljanic, Mr. Mile",male,2.0000,0,0,315037,86625.0,2,S,2,2.0,2
1215,3.0,0,"Smith, Mr. Thomas",male,2.0000,0,0,384461,77500.0,2,Q,2,2.0,2
1216,3.0,1,"Smyth, Miss. Julia",Mujer,2.0000,0,0,335432,77333.0,2,Q,13,2.0,2
1217,3.0,0,"Soholt, Mr. Peter Andreas Lauritz Andersen",male,19.0000,0,0,348124,76500.0,F G73,S,2,2.0,2
1218,3.0,0,"Somerton, Mr. Francis William",male,30.0000,0,0,A.5. 18509,80500.0,2,S,2,2.0,2

### **3.** **Columna sex:** reemplazar valores por "male" y "female"

In [38]:
titanic['sex'] = titanic['sex'].replace('Hombre', 'male')
titanic['sex'] = titanic['sex'].replace('Mujer', 'female')
titanic.head(30)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,2113375.0,B5,S,2,2.0,"St Louis, MO"
1,1.0,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,1515500.0,C22 C26,S,11,2.0,"Montreal, PQ / Chesterville, ON"
2,1.0,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,1515500.0,C22 C26,S,2,2.0,"Montreal, PQ / Chesterville, ON"
3,1.0,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,1515500.0,C22 C26,S,2,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,1515500.0,C22 C26,S,2,2.0,"Montreal, PQ / Chesterville, ON"
5,1.0,1,"Anderson, Mr. Harry",male,48.0000,0,0,19952,265500.0,E12,S,3,2.0,"New York, NY"
6,1.0,1,"Andrews, Miss. Kornelia Theodosia",female,63.0000,1,0,13502,779583.0,D7,S,10,2.0,"Hudson, NY"
7,1.0,0,"Andrews, Mr. Thomas Jr",male,39.0000,0,0,112050,0.0,A36,S,2,2.0,"Belfast, NI"
8,1.0,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0000,2,0,11769,514792.0,C101,S,D,2.0,"Bayside, Queens, NY"
9,1.0,0,"Artagaveytia, Mr. Ramon",male,71.0000,0,0,PC 17609,495042.0,2,C,2,22.0,"Montevideo, Uruguay"
10,1.0,0,"Astor, Col. John Jacob",male,47.0000,1,0,PC 17757,2275250.0,C62 C64,C,2,124.0,"New York, NY"
11,1.0,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.0000,1,0,PC 17757,2275250.0,C62 C64,C,4,2.0,"New York, NY"
12,1.0,1,"Aubart, Mme. Leontine Pauline",female,24.0000,0,0,PC 17477,693000.0,B35,C,9,2.0,"Paris, France"
13,1.0,1,"Barber, Miss. Ellen ""Nellie""",female,26.0000,0,0,19877,788500.0,2,S,6,2.0,2
14,1.0,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0000,0,0,27042,300000.0,A23,S,B,2.0,"Hessle, Yorks"
15,1.0,0,"Baumann, Mr. John D",male,2.0000,0,0,PC 17318,259250.0,2,S,2,2.0,"New York, NY"
16,1.0,0,"Baxter, Mr. Quigg Edmond",male,24.0000,0,1,PC 17558,2475208.0,B58 B60,C,2,2.0,"Montreal, PQ"
17,1.0,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.0000,0,1,PC 17558,2475208.0,B58 B60,C,6,2.0,"Montreal, PQ"
18,1.0,1,"Bazzani, Miss. Albina",female,32.0000,0,0,11813,762917.0,D15,C,8,2.0,2
19,1.0,0,"Beattie, Mr. Thomson",male,36.0000,0,0,13050,752417.0,C6,C,A,2.0,"Winnipeg, MN"
20,1.0,1,"Beckwith, Mr. Richard Leonard",male,37.0000,1,1,11751,525542.0,D35,S,5,2.0,"New York, NY"
21,1.0,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0000,1,1,11751,525542.0,D35,S,5,2.0,"New York, NY"
22,1.0,1,"Behr, Mr. Karl Howell",male,26.0000,0,0,111369,300000.0,C148,C,5,2.0,"New York, NY"
23,1.0,1,"Bidois, Miss. Rosalie",female,42.0000,0,0,PC 17757,2275250.0,2,C,4,2.0,2
24,1.0,1,"Bird, Miss. Ellen",female,29.0000,0,0,PC 17483,2217792.0,C97,S,8,2.0,2
25,1.0,0,"Birnbaum, Mr. Jakob",male,25.0000,0,0,13905,260000.0,2,C,2,148.0,"San Francisco, CA"
26,1.0,1,"Bishop, Mr. Dickinson H",male,25.0000,1,0,11967,910792.0,B49,C,7,2.0,"Dowagiac, MI"
27,1.0,1,"Bishop, Mrs. Dickinson H (Helen Walton)",female,19.0000,1,0,11967,910792.0,B49,C,7,2.0,"Dowagiac, MI"
28,1.0,1,"Bissette, Miss. Amelia",female,35.0000,0,0,PC 17760,1356333.0,C99,S,8,2.0,2
29,1.0,1,"Bjornstrom-Steffansson, Mr. Mauritz Hakan",male,28.0000,0,0,110564,265500.0,C52,S,D,2.0,"Stockholm, Sweden / Washington, DC"


### **4.** **Columna edad:** completar valores NA = asignación mean

In [29]:
mean= titanic['age'].mean()
mean

24.531378178835112

In [37]:
titanic['age']=titanic['age'].fillna(mean)
titanic.head(30)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,2113375.0,B5,S,2,2.0,"St Louis, MO"
1,1.0,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,1515500.0,C22 C26,S,11,2.0,"Montreal, PQ / Chesterville, ON"
2,1.0,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,1515500.0,C22 C26,S,2,2.0,"Montreal, PQ / Chesterville, ON"
3,1.0,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,1515500.0,C22 C26,S,2,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,1515500.0,C22 C26,S,2,2.0,"Montreal, PQ / Chesterville, ON"
5,1.0,1,"Anderson, Mr. Harry",male,48.0000,0,0,19952,265500.0,E12,S,3,2.0,"New York, NY"
6,1.0,1,"Andrews, Miss. Kornelia Theodosia",female,63.0000,1,0,13502,779583.0,D7,S,10,2.0,"Hudson, NY"
7,1.0,0,"Andrews, Mr. Thomas Jr",male,39.0000,0,0,112050,0.0,A36,S,2,2.0,"Belfast, NI"
8,1.0,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0000,2,0,11769,514792.0,C101,S,D,2.0,"Bayside, Queens, NY"
9,1.0,0,"Artagaveytia, Mr. Ramon",male,71.0000,0,0,PC 17609,495042.0,2,C,2,22.0,"Montevideo, Uruguay"
10,1.0,0,"Astor, Col. John Jacob",male,47.0000,1,0,PC 17757,2275250.0,C62 C64,C,2,124.0,"New York, NY"
11,1.0,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.0000,1,0,PC 17757,2275250.0,C62 C64,C,4,2.0,"New York, NY"
12,1.0,1,"Aubart, Mme. Leontine Pauline",female,24.0000,0,0,PC 17477,693000.0,B35,C,9,2.0,"Paris, France"
13,1.0,1,"Barber, Miss. Ellen ""Nellie""",female,26.0000,0,0,19877,788500.0,2,S,6,2.0,2
14,1.0,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0000,0,0,27042,300000.0,A23,S,B,2.0,"Hessle, Yorks"
15,1.0,0,"Baumann, Mr. John D",male,2.0000,0,0,PC 17318,259250.0,2,S,2,2.0,"New York, NY"
16,1.0,0,"Baxter, Mr. Quigg Edmond",male,24.0000,0,1,PC 17558,2475208.0,B58 B60,C,2,2.0,"Montreal, PQ"
17,1.0,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.0000,0,1,PC 17558,2475208.0,B58 B60,C,6,2.0,"Montreal, PQ"
18,1.0,1,"Bazzani, Miss. Albina",female,32.0000,0,0,11813,762917.0,D15,C,8,2.0,2
19,1.0,0,"Beattie, Mr. Thomson",male,36.0000,0,0,13050,752417.0,C6,C,A,2.0,"Winnipeg, MN"
20,1.0,1,"Beckwith, Mr. Richard Leonard",male,37.0000,1,1,11751,525542.0,D35,S,5,2.0,"New York, NY"
21,1.0,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0000,1,1,11751,525542.0,D35,S,5,2.0,"New York, NY"
22,1.0,1,"Behr, Mr. Karl Howell",male,26.0000,0,0,111369,300000.0,C148,C,5,2.0,"New York, NY"
23,1.0,1,"Bidois, Miss. Rosalie",female,42.0000,0,0,PC 17757,2275250.0,2,C,4,2.0,2
24,1.0,1,"Bird, Miss. Ellen",female,29.0000,0,0,PC 17483,2217792.0,C97,S,8,2.0,2
25,1.0,0,"Birnbaum, Mr. Jakob",male,25.0000,0,0,13905,260000.0,2,C,2,148.0,"San Francisco, CA"
26,1.0,1,"Bishop, Mr. Dickinson H",male,25.0000,1,0,11967,910792.0,B49,C,7,2.0,"Dowagiac, MI"
27,1.0,1,"Bishop, Mrs. Dickinson H (Helen Walton)",female,19.0000,1,0,11967,910792.0,B49,C,7,2.0,"Dowagiac, MI"
28,1.0,1,"Bissette, Miss. Amelia",female,35.0000,0,0,PC 17760,1356333.0,C99,S,8,2.0,2
29,1.0,1,"Bjornstrom-Steffansson, Mr. Mauritz Hakan",male,28.0000,0,0,110564,265500.0,C52,S,D,2.0,"Stockholm, Sweden / Washington, DC"

### **5.** **Columna embarked:** completar valores NA = asignación "S"

In [36]:
titanic['embarked']=titanic['embarked'].fillna('S')
titanic.head(30)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,2113375.0,B5,S,2,2.0,"St Louis, MO"
1,1.0,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,1515500.0,C22 C26,S,11,2.0,"Montreal, PQ / Chesterville, ON"
2,1.0,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,1515500.0,C22 C26,S,2,2.0,"Montreal, PQ / Chesterville, ON"
3,1.0,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,1515500.0,C22 C26,S,2,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,1515500.0,C22 C26,S,2,2.0,"Montreal, PQ / Chesterville, ON"
5,1.0,1,"Anderson, Mr. Harry",male,48.0000,0,0,19952,265500.0,E12,S,3,2.0,"New York, NY"
6,1.0,1,"Andrews, Miss. Kornelia Theodosia",female,63.0000,1,0,13502,779583.0,D7,S,10,2.0,"Hudson, NY"
7,1.0,0,"Andrews, Mr. Thomas Jr",male,39.0000,0,0,112050,0.0,A36,S,2,2.0,"Belfast, NI"
8,1.0,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0000,2,0,11769,514792.0,C101,S,D,2.0,"Bayside, Queens, NY"
9,1.0,0,"Artagaveytia, Mr. Ramon",male,71.0000,0,0,PC 17609,495042.0,2,C,2,22.0,"Montevideo, Uruguay"
10,1.0,0,"Astor, Col. John Jacob",male,47.0000,1,0,PC 17757,2275250.0,C62 C64,C,2,124.0,"New York, NY"
11,1.0,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.0000,1,0,PC 17757,2275250.0,C62 C64,C,4,2.0,"New York, NY"
12,1.0,1,"Aubart, Mme. Leontine Pauline",female,24.0000,0,0,PC 17477,693000.0,B35,C,9,2.0,"Paris, France"
13,1.0,1,"Barber, Miss. Ellen ""Nellie""",female,26.0000,0,0,19877,788500.0,2,S,6,2.0,2
14,1.0,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0000,0,0,27042,300000.0,A23,S,B,2.0,"Hessle, Yorks"
15,1.0,0,"Baumann, Mr. John D",male,2.0000,0,0,PC 17318,259250.0,2,S,2,2.0,"New York, NY"
16,1.0,0,"Baxter, Mr. Quigg Edmond",male,24.0000,0,1,PC 17558,2475208.0,B58 B60,C,2,2.0,"Montreal, PQ"
17,1.0,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.0000,0,1,PC 17558,2475208.0,B58 B60,C,6,2.0,"Montreal, PQ"
18,1.0,1,"Bazzani, Miss. Albina",female,32.0000,0,0,11813,762917.0,D15,C,8,2.0,2
19,1.0,0,"Beattie, Mr. Thomson",male,36.0000,0,0,13050,752417.0,C6,C,A,2.0,"Winnipeg, MN"
20,1.0,1,"Beckwith, Mr. Richard Leonard",male,37.0000,1,1,11751,525542.0,D35,S,5,2.0,"New York, NY"
21,1.0,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0000,1,1,11751,525542.0,D35,S,5,2.0,"New York, NY"
22,1.0,1,"Behr, Mr. Karl Howell",male,26.0000,0,0,111369,300000.0,C148,C,5,2.0,"New York, NY"
23,1.0,1,"Bidois, Miss. Rosalie",female,42.0000,0,0,PC 17757,2275250.0,2,C,4,2.0,2
24,1.0,1,"Bird, Miss. Ellen",female,29.0000,0,0,PC 17483,2217792.0,C97,S,8,2.0,2
25,1.0,0,"Birnbaum, Mr. Jakob",male,25.0000,0,0,13905,260000.0,2,C,2,148.0,"San Francisco, CA"
26,1.0,1,"Bishop, Mr. Dickinson H",male,25.0000,1,0,11967,910792.0,B49,C,7,2.0,"Dowagiac, MI"
27,1.0,1,"Bishop, Mrs. Dickinson H (Helen Walton)",female,19.0000,1,0,11967,910792.0,B49,C,7,2.0,"Dowagiac, MI"
28,1.0,1,"Bissette, Miss. Amelia",female,35.0000,0,0,PC 17760,1356333.0,C99,S,8,2.0,2
29,1.0,1,"Bjornstrom-Steffansson, Mr. Mauritz Hakan",male,28.0000,0,0,110564,265500.0,C52,S,D,2.0,"Stockholm, Sweden / Washington, DC"

### Verificación de valores finales

In [39]:
titanic.isna().sum()

pclass       0
survived     0
name         0
sex          0
age          0
sibsp        0
parch        0
ticket       0
fare         0
cabin        0
embarked     0
boat         0
body         0
home.dest    0
dtype: int64