`MACHINE LEARNING | ANALÍA ELIZABETH GOMORY | ARGENTINA – SALTA 4400 | 2024`

**by Analía Elizabeth Gomory**

* ae.gomory@gmail.com

* http://www.linkedin.com/in/elizabeth-gomory-9240b1217

* https://ae-gomory.itch.io

* https://github.com/ElizabethGomory

* https://www.credly.com/users/analia-gomory

* https://orcid.org/0009-0003-0498-7658

* Descarga de librerías y archivos

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import KNNImputer
from sklearn.model_selection import train_test_split as tts
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score as accs
from sklearn.metrics import precision_score as prs
from sklearn.metrics import recall_score as recs
from sklearn.metrics import f1_score as f1s

In [ ]:
test = pd.read_csv('/content/test.csv')
train = pd.read_csv('/content/train.csv')

#A. Descripción de valores faltantes para cada variable de las bases de datos.

## Test

In [ ]:
test.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [ ]:
test.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [ ]:
print ((test.Cabin.isnull().sum()*100)/test.shape[0])

78.22966507177034

In [ ]:
test.shape

(418, 11)

## Train

In [ ]:
train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
print((train.Cabin.isnull().sum()*100)/train.shape[0])

77.10437710437711

In [ ]:
train.shape

(891, 12)

# B. Completar valores Faltantes en bases de datos.

`No se reemplazarán los valores de "Cabin" en ambas bases de datos, ya que los valores nulos son mayores al 75%, por lo que se decidió no considerarlos en el modelo.`

In [ ]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    object
 3   Sex          418 non-null    object
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object
 10  Embarked     418 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
pre_columns=["Sex", "Embarked"]
for c in pre_columns:
    encoder = LabelEncoder()
    train [c] = encoder.fit_transform(train [c]. astype("str"))
    test [c] = encoder.fit_transform(test [c].astype("str"))

train.info()
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    int64
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     891 non-null    int64
dtypes: float64(2), int64(7), object(3)
memory usage: 83.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    object
 3   Sex          418 non-null    int64
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object
 10  Embarked     418 non-null    int64
dtypes: float64(2), int64(6), object(3)
memory usage: 36.0+ KB

In [ ]:
x_columns = ['Age', 'Embarked', 'Fare']
imputer = KNNImputer (n_neighbors=3,weights= "uniform")
train[x_columns] = imputer.fit_transform(train[x_columns])
test[x_columns] = imputer.fit_transform(test[x_columns])

In [ ]:
display(test[x_columns].info())
print(test.isnull().sum())
display(train[x_columns].info())
print(train.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Age       418 non-null    float64
 1   Embarked  418 non-null    float64
 2   Fare      418 non-null    float64
dtypes: float64(3)
memory usage: 9.9 KB

None

PassengerId      0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          327
Embarked         0
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Age       891 non-null    float64
 1   Embarked  891 non-null    float64
 2   Fare      891 non-null    float64
dtypes: float64(3)
memory usage: 21.0 KB

None

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

# C. Ajustar Modelo de Árbol de Decisión.

`Se decidió trabajar con las columnas de: Pclass, Sex, Age, SibSp, Parch, Faree y Embarked; para el entrenamiento, el resto de las columnas continen valores únicos que resultarían en un subajuste.`

In [ ]:
col = ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']

label_col = 'Survived'
seed_num = 10
x, y = train[col], train[label_col]

print(x.columns)

Index(['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked'], dtype='object')

In [ ]:
x_train, x_val, y_train, y_val = tts (x, y, test_size=0.3, random_state=seed_num)

In [ ]:
ard = DecisionTreeClassifier (random_state=seed_num)
ard.fit (x_train, y_train)

DecisionTreeClassifier(random_state=10)

#  D. Entrenamiento del Modelo

In [ ]:
y_pred = ard.predict(x_val)
acc = accs(y_val, y_pred)
pre = prs (y_val, y_pred)
rec = recs (y_val, y_pred)
f1 = f1s (y_val, y_pred)

print ("Accuracy: ", acc)
print ("Precision: ", pre)
print ("Recall: ", rec)
print ("F1: ", f1)

Accuracy:  0.8022388059701493
Precision:  0.7070707070707071
Recall:  0.7446808510638298
F1:  0.7253886010362695